import Control.Monad
import qualified Control.Exception as E
import System.IO

handler (E.ErrorCall s) = putStrLn $ "*** Exception"

incomplete1 0 = [undefined]
incomplete1 n = n:(incomplete1 $ n-1)
incomplete2 0 = undefined
incomplete2 n = n:(incomplete2 $ n-1)

main = do 
  hSetBuffering stdout NoBuffering
  forM_ codelist $ \code -> do 
    forM_ [0..2] $ \x -> do 
      E.catch (print $ code $ incomplete1 x) handler
      E.catch (print $ code $ incomplete2 x) handler
    putStrLn "-----------------------"

codelist = [

  ((\x16 -> (\x17 -> ((\x18 -> x17) x17))) (id (undefined :: Int))),
  (\x16 -> ((seq id) (((\x17 -> (\x18 -> x16)) ((seq id) x16)) (((\x17 -> (\x18 -> (\x19 -> (undefined :: Int)))) x16) ((\x17 -> x16) x16))))),
  (\x16 -> (((\x17 -> (\x18 -> ((\x19 -> x19) x18))) ((\x17 -> x16) (undefined :: Int))) ((\x17 -> x16) ((\x17 -> (\x18 -> x16)) x16)))),
  ((\x16 -> (((\x17 -> seq) (id (undefined :: Int))) (\x17 -> (undefined :: Int)))) (undefined :: Int)),
  ((\x16 -> (\x17 -> x17)) ((id seq) ((\x16 -> (undefined :: Int)) (id ((\x16 -> (undefined :: Int)) (\x16 -> x16)))))),
  (seq ((((\x16 -> id) (undefined :: Int)) seq) (undefined :: Int))),
  (seq id),
  (\x16 -> x16),
  (\x16 -> ((\x17 -> x16) (((\x17 -> id) (\x17 -> (\x18 -> (undefined :: Int)))) (id (undefined :: Int))))),
  (((\x16 -> ((\x17 -> (\x18 -> (\x19 -> x19))) (undefined :: Int))) (undefined :: Int)) ((\x16 -> (undefined :: Int)) (((\x16 -> (\x17 -> (\x18 -> (undefined :: Int)))) (undefined :: Int)) (undefined :: Int)))),
  (seq id),
  (seq id),
  (seq (((((\x16 -> (\x17 -> id)) (undefined :: Int)) (id seq)) (\x16 -> id)) (undefined :: Int))),
  (seq id),
  ((\x16 -> (seq (\x17 -> (undefined :: Int)))) ((\x16 -> (\x17 -> (id (undefined :: Int)))) (undefined :: Int))),
  (((\x16 -> seq) (undefined :: Int)) (\x16 -> (undefined :: Int))),
  (\x16 -> (((\x17 -> (\x18 -> x16)) x16) (\x17 -> ((\x18 -> (\x19 -> x16)) (\x18 -> (\x19 -> (\x20 -> x17))))))),
  (seq id),
  (((\x16 -> seq) (undefined :: Int)) ((\x16 -> id) ((\x16 -> (\x17 -> x16)) (undefined :: Int)))),
  (seq (\x16 -> (undefined :: Int))),
  (seq id),
  (\x16 -> ((seq id) ((\x17 -> x16) x16))),
  (\x16 -> ((\x17 -> ((\x18 -> x16) (undefined :: Int))) x16)),
  ((\x16 -> (\x17 -> ((seq (seq (undefined :: Int))) x17))) (\x16 -> (((\x17 -> seq) (undefined :: Int)) id))),
  (((((\x16 -> (\x17 -> (\x18 -> seq))) (\x16 -> (\x17 -> (undefined :: Int)))) (undefined :: Int)) ((id (id (\x16 -> (\x17 -> (undefined :: Int))))) (undefined :: Int))) ((id seq) ((\x16 -> (undefined :: Int)) (undefined :: Int)))),
  (((\x16 -> ((\x17 -> (\x18 -> (\x19 -> x19))) (undefined :: Int))) ((\x16 -> (undefined :: Int)) ((seq (undefined :: Int)) (undefined :: Int)))) ((((\x16 -> (\x17 -> (\x18 -> (\x19 -> (\x20 -> (undefined :: Int)))))) ((\x16 -> (\x17 -> x16)) (undefined :: Int))) ((\x16 -> (\x17 -> (\x18 -> (undefined :: Int)))) (undefined :: Int))) ((\x16 -> (id (undefined :: Int))) (\x16 -> (undefined :: Int))))),
  (seq ((((\x16 -> (\x17 -> seq)) (undefined :: Int)) (\x16 -> (\x17 -> (undefined :: Int)))) ((\x16 -> (undefined :: Int)) (id (id (undefined :: Int)))))),
  (seq (\x16 -> (undefined :: Int))),
  (\x16 -> ((((\x17 -> (\x18 -> (\x19 -> x16))) (undefined :: Int)) x16) (((\x17 -> id) (id (undefined :: Int))) (((\x17 -> (\x18 -> (\x19 -> (\x20 -> (undefined :: Int))))) (undefined :: Int)) ((\x17 -> (undefined :: Int)) x16))))),
  (seq (seq (id (undefined :: Int)))),
  ((\x16 -> (\x17 -> x17)) (undefined :: Int)),
  ((\x16 -> (seq id)) (undefined :: Int)),
  ((((\x16 -> (\x17 -> seq)) (undefined :: Int)) (undefined :: Int)) (\x16 -> (undefined :: Int))),
  (id (seq (id (\x16 -> seq x16 id) (undefined :: Int)))),
  (((\x16 -> seq) ((\x16 -> (undefined :: Int)) (\x16 -> (undefined :: Int)))) (((\x16 -> seq) (undefined :: Int)) (id (undefined :: Int)))),
  (\x16 -> ((seq id) ((\x17 -> x16) (undefined :: Int)))),
  ((((\x16 -> (\x17 -> seq)) (\x16 -> x16)) id) (seq (id (undefined :: Int)))),
  (((\x16 -> seq) (undefined :: Int)) (\x16 -> (undefined :: Int))),
  ((((\x16 -> (\x17 -> seq)) (undefined :: Int)) ((\x16 -> (\x17 -> (\x18 -> (\x19 -> (\x20 -> (undefined :: Int)))))) (id (undefined :: Int)))) (seq (undefined :: Int))),
  (seq ((id ((\x16 -> seq) (undefined :: Int))) (undefined :: Int))),
  ((\x16 -> (seq (\x17 -> x17))) (id ((\x16 -> (x16 (\x17 -> id))) (\x16 -> (undefined :: Int))))),
  (seq id),
  (seq ((\x16 -> (\x17 -> (undefined :: Int))) (\x16 -> ((\x17 -> (\x18 -> (\x19 -> x18))) (id (undefined :: Int)))))),
  (\x16 -> (((((\x17 -> (\x18 -> seq)) (\x17 -> (\x18 -> (undefined :: Int)))) (\x17 -> (id (undefined :: Int)))) ((\x17 -> ((\x18 -> id) x16)) x16)) (((\x17 -> (\x18 -> x16)) (id (undefined :: Int))) x16))),
  (((((\x16 -> (\x17 -> (\x18 -> (\x19 -> x18)))) (undefined :: Int)) (id (id (undefined :: Int)))) (((\x16 -> seq) (\x16 -> (\x17 -> (\x18 -> (undefined :: Int))))) id)) (seq (undefined :: Int))),
  (seq id),
  (seq id),
  (seq ((id (id (\x16 -> (seq (undefined :: Int))))) (id (id (id (undefined :: Int)))))),
  (\x16 -> x16),
  (\x16 -> x16),
  (((((\x16 -> ((\x17 -> (\x18 -> (\x19 -> seq))) (\x17 -> x17))) (undefined :: Int)) (\x16 -> (id (undefined :: Int)))) (id (id (undefined :: Int)))) id),
  ((((\x16 -> (\x17 -> seq)) (\x16 -> (\x17 -> x16))) (undefined :: Int)) ((id (\x16 -> (seq (undefined :: Int)))) (id (undefined :: Int)))),
  (((((\x16 -> (\x17 -> (\x18 -> seq))) (\x16 -> (\x17 -> (undefined :: Int)))) (seq (undefined :: Int))) (\x16 -> (undefined :: Int))) (\x16 -> (undefined :: Int))),
  (seq ((\x16 -> (\x17 -> (undefined :: Int))) (undefined :: Int))),
  (((\x16 -> seq) (id ((\x16 -> (undefined :: Int)) (seq id)))) ((\x16 -> (\x17 -> (undefined :: Int))) ((\x16 -> (id (undefined :: Int))) (undefined :: Int)))),
  (seq id),
  (((((\x16 -> (\x17 -> (\x18 -> (\x19 -> (\x20 -> x20))))) (id ((\x16 -> (undefined :: Int)) (undefined :: Int)))) (\x16 -> (undefined :: Int))) (undefined :: Int)) (((\x16 -> id) (undefined :: Int)) (((id (\x16 -> id)) (undefined :: Int)) (undefined :: Int)))),
  (seq (seq (id (((\x16 -> (\x17 -> (undefined :: Int))) (undefined :: Int)) (undefined :: Int))))),
  (seq ((((\x16 -> id) (undefined :: Int)) (\x16 -> ((\x17 -> (\x18 -> (undefined :: Int))) (undefined :: Int)))) (undefined :: Int))),
  (((((\x16 -> (\x17 -> (\x18 -> seq))) (id (undefined :: Int))) ((\x16 -> (undefined :: Int)) (\x16 -> (undefined :: Int)))) (((\x16 -> id) (undefined :: Int)) (undefined :: Int))) (seq (id (undefined :: Int)))),
  (seq id),
  ((((\x16 -> (\x17 -> seq)) (undefined :: Int)) (undefined :: Int)) (\x16 -> (undefined :: Int))),
  (seq ((\x16 -> id) ((\x16 -> (undefined :: Int)) (\x16 -> (id (undefined :: Int)))))),
  (((\x16 -> (\x17 -> ((\x18 -> (\x19 -> x19)) x16))) (undefined :: Int)) (((id (\x16 -> id)) (undefined :: Int)) (undefined :: Int))),
  (((\x16 -> seq) (id (id (undefined :: Int)))) (seq ((seq ((\x16 -> (undefined :: Int)) (\x16 -> (undefined :: Int)))) (id (id (undefined :: Int)))))),
  (((\x16 -> seq) (undefined :: Int)) ((id (id seq)) ((seq (undefined :: Int)) (undefined :: Int)))),
  (seq ((((\x16 -> ((\x17 -> id) (undefined :: Int))) (\x16 -> (\x17 -> (\x18 -> (undefined :: Int))))) (\x16 -> id)) (undefined :: Int))),
  (\x16 -> ((seq (\x17 -> (undefined :: Int))) x16)),
  ((((\x16 -> ((\x17 -> x17) (\x17 -> (\x18 -> (\x19 -> x19))))) (\x16 -> ((\x17 -> (undefined :: Int)) (undefined :: Int)))) (undefined :: Int)) (\x16 -> (undefined :: Int))),
  (seq id),
  (((\x16 -> seq) ((\x16 -> (undefined :: Int)) (\x16 -> (undefined :: Int)))) ((id seq) (undefined :: Int))),
  (\x16 -> (((\x17 -> (\x18 -> x16)) (((\x17 -> (\x18 -> (\x19 -> x16))) (\x17 -> (\x18 -> (\x19 -> x16)))) (\x17 -> ((\x18 -> id) (\x18 -> x16))))) ((\x17 -> x16) (\x17 -> (\x18 -> (undefined :: Int)))))),
  ((\x16 -> (\x17 -> (((\x18 -> (\x19 -> x18)) ((\x18 -> x17) (\x18 -> x17))) (\x18 -> x17)))) (\x16 -> (id ((\x17 -> (id (undefined :: Int))) (x16 (undefined :: Int)))))),
  ((\x16 -> (((\x17 -> seq) (undefined :: Int)) (\x17 -> (undefined :: Int)))) (seq ((seq (undefined :: Int)) (undefined :: Int)))),
  (\x16 -> ((seq (\x17 -> (id (undefined :: Int)))) x16)),
  (seq (\x16 -> (id ((\x17 -> x16) (\x17 -> (\x18 -> x17)))))),
  ((((\x16 -> (\x17 -> seq)) ((seq (undefined :: Int)) ((\x16 -> (undefined :: Int)) (undefined :: Int)))) (seq (undefined :: Int))) ((((\x16 -> (\x17 -> seq)) ((\x16 -> (undefined :: Int)) (undefined :: Int))) (\x16 -> (undefined :: Int))) (id (undefined :: Int)))),
  (((\x16 -> seq) (\x16 -> (id (undefined :: Int)))) ((id seq) (((\x16 -> id) (undefined :: Int)) (undefined :: Int)))),
  (\x16 -> ((seq (seq (undefined :: Int))) (((\x17 -> (\x18 -> x18)) x16) x16))),
  (seq id),
  (\x16 -> ((\x17 -> x16) (undefined :: Int))),
  (((\x16 -> seq) (undefined :: Int)) ((\x16 -> ((\x17 -> id) (undefined :: Int))) (undefined :: Int))),
  (seq id),
  (\x16 -> x16),
  (seq (\x16 -> x16)),
  (seq (seq (id ((\x16 -> (undefined :: Int)) (undefined :: Int))))),
  (\x16 -> ((\x17 -> ((\x18 -> ((\x19 -> x16) (\x19 -> (undefined :: Int)))) x16)) ((\x17 -> (\x18 -> x16)) ((\x17 -> (\x18 -> x16)) (\x17 -> ((\x18 -> x16) x16)))))),
  (\x16 -> x16),
  (((\x16 -> (\x17 -> (\x18 -> x18))) ((seq (undefined :: Int)) ((\x16 -> (undefined :: Int)) (undefined :: Int)))) (id ((seq (undefined :: Int)) (undefined :: Int)))),
  ((\x16 -> (\x17 -> x17)) (\x16 -> (\x17 -> (undefined :: Int)))),
  (((\x16 -> seq) (\x16 -> ((\x17 -> (\x18 -> x16)) (id (undefined :: Int))))) ((\x16 -> id) id)),
  ((((((\x16 -> (\x17 -> (\x18 -> (\x19 -> seq)))) (\x16 -> (undefined :: Int))) (undefined :: Int)) (undefined :: Int)) (id (undefined :: Int))) (\x16 -> ((\x17 -> (id (undefined :: Int))) (undefined :: Int)))),
  ((((\x16 -> (\x17 -> seq)) (undefined :: Int)) (id (undefined :: Int))) (seq (undefined :: Int))),
  (((\x16 -> (\x17 -> (((\x18 -> seq) (\x18 -> x16)) (\x18 -> (undefined :: Int))))) (undefined :: Int)) (((id (\x16 -> id)) (id (undefined :: Int))) (undefined :: Int))),
  (((\x16 -> seq) (seq ((\x16 -> (undefined :: Int)) (id (undefined :: Int))))) ((\x16 -> ((\x17 -> (\x18 -> (undefined :: Int))) (id (undefined :: Int)))) ((\x16 -> (\x17 -> (undefined :: Int))) (undefined :: Int)))),
  (seq ((\x16 -> (\x17 -> (undefined :: Int))) ((\x16 -> (\x17 -> (x17 (\x18 -> x16)))) (undefined :: Int)))),
  (\x16 -> ((\x17 -> x16) ((\x17 -> (\x18 -> x17)) (undefined :: Int)))),
  (((\x16 -> seq) (seq id)) id),
  (seq (seq (id (undefined :: Int)))),
  ((\x16 -> (seq (seq (id (undefined :: Int))))) (undefined :: Int)),
  (((\x16 -> (\x17 -> (\x18 -> x18))) ((\x16 -> (\x17 -> (\x18 -> (\x19 -> x19)))) (id (undefined :: Int)))) (((\x16 -> id) ((seq (undefined :: Int)) (undefined :: Int))) ((seq (undefined :: Int)) (undefined :: Int)))),
  (\x16 -> (((\x17 -> (seq (\x18 -> (undefined :: Int)))) x16) ((\x17 -> x16) ((\x17 -> (\x18 -> (\x19 -> (undefined :: Int)))) (\x17 -> (undefined :: Int)))))),
  (seq ((\x16 -> (\x17 -> (undefined :: Int))) ((\x16 -> (\x17 -> (\x18 -> (undefined :: Int)))) (id (undefined :: Int))))),
  (seq id),
  (((\x16 -> seq) (undefined :: Int)) (seq (undefined :: Int))),
  (\x16 -> ((seq id) ((seq id) ((\x17 -> x16) x16)))),
  (((\x16 -> seq) (id (undefined :: Int))) id),
  (\x16 -> (((\x17 -> (seq id)) (((\x17 -> (\x18 -> (\x19 -> x17))) (undefined :: Int)) (undefined :: Int))) x16)),
  (\x16 -> ((\x17 -> x16) ((((\x17 -> seq) (\x17 -> x16)) (\x17 -> (undefined :: Int))) x16))),
  (((\x16 -> ((\x17 -> seq) (undefined :: Int))) (undefined :: Int)) ((id (\x16 -> (\x17 -> (undefined :: Int)))) (undefined :: Int)))  ]
